library(tidyr)
library(dplyr)
setwd("C:\\Users\\MohammadA\\Dropbox\\Data_Science\\Springboard\\Track 1\\Task_1")
data_set <- read.table("refine_original.csv", header = TRUE,sep = ",")
data_set$company <-tolower(data_set$company)
data_set<-data_set %>% separate(Product.code...number, c("product_code", "product_number"), sep = "-", remove = TRUE, convert = FALSE)
data_set <- data_set %>% mutate(category = recode(product_code, 'p'="Smartphone", 'v'="TV",'x'="Laptop",'q'="Tablet"))
data_set <- data_set %>% mutate(full_address = paste(address, city, country, sep=","))
data_set <- data_set %>% mutate(company_philips = ifelse(company=="phillips",1,0))
data_set <- data_set %>% mutate(company_akzo = ifelse(company=="akzo",1,0))
data_set <- data_set %>% mutate(company_van_houten = ifelse(company=="van houten",1,0))
data_set <- data_set %>% mutate(company_unilever = ifelse(company=="unilever",1,0))
data_set <- data_set %>% mutate(product_smartphone = ifelse(category=="Smartphone",1,0))
data_set <- data_set %>% mutate(product_tv = ifelse(category=="TV",1,0))
data_set <- data_set %>% mutate(product_laptop = ifelse(category=="Laptop",1,0))
data_set <- data_set %>% mutate(product_tablet = ifelse(category=="Tablet",1,0))